[project]
name = "ml4g-project-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "lightgbm>=4.6.0",
    "pybedtools>=0.12.0",
    "scikit-learn>=1.6.1",
]
